spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  sql:
    init:
      mode: always
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=600s
  jackson:
    time-zone: ${APP_TIMEZONE:America/El_Salvador}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION:86400000}
  timezone: ${APP_TIMEZONE:America/El_Salvador}

logging:
  level:
    com.gerson.coworking: INFO
    org.springframework: WARN
    org.hibernate: WARN